import type { ClassRoom, HistoryRecord, NavItem, OperatorMember, Role, StaffMember, Student, Teacher } from './types';

export const roles: Role[] = [
  {
    id: 'diretor',
    label: 'Diretor',
    name: 'Diretor Marcos Almeida',
    initials: 'DA',
    mode: 'admin',
    description: 'Visão completa da escola, indicadores gerais e gestão de usuários.',
    scope: 'Todas as turmas, alunos, professores, operadores e relatórios.',
  },
  {
    id: 'secretaria',
    label: 'Secretaria',
    name: 'Secretaria Ana Costa',
    initials: 'SA',
    mode: 'admin',
    description: 'Operação administrativa da escola com cadastro e organização das turmas.',
    scope: 'Alunos, turmas, vínculos, operadores e relatórios de presença.',
  },
  {
    id: 'professor',
    label: 'Professor',
    name: 'Professor Lucas Silva',
    initials: 'LS',
    mode: 'routine',
    description: 'Rotina simples para consultar turmas, realizar chamada e acompanhar histórico.',
    scope: 'Somente turmas vinculadas ao professor.',
  },
  {
    id: 'operador',
    label: 'Operador / Substituto',
    name: 'Operador Rafael Lima',
    initials: 'OP',
    mode: 'routine',
    description: 'Acesso autorizado para realizar chamada em turmas liberadas pela Secretaria.',
    scope: 'Turmas autorizadas temporária ou permanentemente.',
  },
];

export const navItems: NavItem[] = [
  { id: 'inicio', label: 'Início', icon: 'bi-grid-1x2-fill' },
  { id: 'turmas', label: 'Turmas', icon: 'bi-mortarboard-fill' },
  { id: 'consulta', label: 'Consulta', icon: 'bi-search' },
  { id: 'configuracoes', label: 'Ajustes', icon: 'bi-sliders' },
];

export const classes: ClassRoom[] = [
  {
    id: '6a',
    grade: '6º Ano A',
    period: 'Manhã',
    time: '07:30 - 11:30',
    school: 'Escola Municipal Professora Helena Kolody',
    students: 28,
    teacher: 'Lucas Silva',
    status: 'pending',
    accent: 'teal',
  },
  {
    id: '7b',
    grade: '7º Ano B',
    period: 'Tarde',
    time: '13:00 - 17:00',
    school: 'Escola Municipal Professor Antônio dos Santos',
    students: 26,
    teacher: 'Lucas Silva',
    status: 'scheduled',
    accent: 'blue',
  },
  {
    id: '8a',
    grade: '8º Ano A',
    period: 'Manhã',
    time: '07:30 - 11:30',
    school: 'Escola Municipal Tiradentes',
    students: 27,
    teacher: 'Lucas Silva',
    status: 'next',
    accent: 'teal',
  },
];

export const students: Student[] = [
  {
    id: 1,
    matricula: '2024-00124',
    name: 'Ana Clara de Lima',
    classId: '6a',
    status: 'present',
    rate: 96,
    responsible: 'Regina Célia de Lima',
    phone: '(41) 99841-2210',
    birthDate: '14/03/2012',
    observations: [
      {
        id: 'obs-1',
        date: '24/05/2024',
        time: '08:15',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'present',
        description: 'Excelente participação na resolução dos exercícios no quadro.',
      },
    ],
  },
  {
    id: 2,
    matricula: '2024-00125',
    name: 'Bruno Henrique Souza',
    classId: '6a',
    status: 'absent',
    rate: 86,
    responsible: 'Maria de Fátima Souza',
    phone: '(41) 98754-3321',
    birthDate: '22/07/2012',
    observations: [
      {
        id: 'obs-2',
        date: '24/05/2024',
        time: '07:45',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'absent',
        description: 'Matou aula / saiu da sala no início do período sem autorização.',
      },
      {
        id: 'obs-3',
        date: '22/05/2024',
        time: '09:30',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'absent',
        description: 'Aluno não prestou atenção e foi para a quadra durante a aula.',
      },
    ],
  },
  {
    id: 3,
    matricula: '2024-00126',
    name: 'Carlos Eduardo Martins',
    classId: '6a',
    status: 'late',
    rate: 88,
    responsible: 'Roberto Martins',
    phone: '(41) 99123-4567',
    birthDate: '09/11/2012',
    observations: [
      {
        id: 'obs-4',
        date: '24/05/2024',
        time: '08:00',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'late',
        description: 'Chegou 30 minutos atrasado e com conversa excessiva atrapalhando a explicação.',
      },
    ],
  },
  {
    id: 4,
    matricula: '2024-00127',
    name: 'Danielly Vitória Campos',
    classId: '6a',
    status: 'excused',
    rate: 92,
    responsible: 'Solange Campos',
    phone: '(41) 99988-1122',
    birthDate: '03/01/2012',
    observations: [
      {
        id: 'obs-5',
        date: '24/05/2024',
        time: '07:35',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'excused',
        description: 'Falta justificada por atestado médico odontológico entregue pela mãe.',
      },
    ],
  },
  {
    id: 5,
    matricula: '2024-00128',
    name: 'Eduardo Gabriel Pereira',
    classId: '6a',
    status: 'present',
    rate: 94,
    responsible: 'Gabriel Pereira',
    phone: '(41) 99234-5566',
    birthDate: '18/05/2012',
    observations: [
      {
        id: 'obs-6',
        date: '23/05/2024',
        time: '10:10',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'present',
        description: 'Uso indevido de celular jogando durante a explicação do conteúdo.',
      },
    ],
  },
  {
    id: 6,
    matricula: '2024-00129',
    name: 'Giovanna Ribeiro da Silva',
    classId: '6a',
    status: 'present',
    rate: 98,
    responsible: 'Carla Ribeiro',
    phone: '(41) 99345-6677',
    birthDate: '30/08/2012',
    observations: [
      {
        id: 'obs-7',
        date: '20/05/2024',
        time: '08:30',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'present',
        description: 'Líder eleita da turma, auxiliou os colegas nas atividades.',
      },
    ],
  },
  {
    id: 7,
    matricula: '2024-00130',
    name: 'Isabela Cristina Moreira',
    classId: '6a',
    status: 'open',
    rate: 91,
    responsible: 'Cristina Moreira',
    phone: '(41) 99456-7788',
    birthDate: '12/10/2012',
    observations: [
      {
        id: 'obs-8',
        date: '23/05/2024',
        time: '09:00',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'present',
        description: 'Aluno desatento e dormindo com a cabeça na carteira durante a aula.',
      },
    ],
  },
  {
    id: 8,
    matricula: '2024-00201',
    name: 'João Miguel Santos',
    classId: '7b',
    status: 'present',
    rate: 93,
    responsible: 'Patrícia Santos',
    phone: '(41) 99567-8899',
    birthDate: '05/04/2011',
    observations: [
      {
        id: 'obs-9',
        date: '21/05/2024',
        time: '14:20',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'present',
        description: 'Transferido de turma e adaptando-se bem ao ritmo da turma.',
      },
    ],
  },
  {
    id: 9,
    matricula: '2024-00202',
    name: 'Laura Beatriz Oliveira',
    classId: '7b',
    status: 'absent',
    rate: 82,
    responsible: 'Marcos Oliveira',
    phone: '(41) 99678-9900',
    birthDate: '19/09/2011',
    observations: [
      {
        id: 'obs-10',
        date: '21/05/2024',
        time: '15:10',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'absent',
        description: 'Matou a 3ª aula para ficar no pátio com alunos de outra turma.',
      },
      {
        id: 'obs-11',
        date: '17/05/2024',
        time: '13:40',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'absent',
        description: 'Não entrou na sala após o intervalo.',
      },
    ],
  },
  {
    id: 10,
    matricula: '2024-00301',
    name: 'Miguel Augusto Rocha',
    classId: '8a',
    status: 'present',
    rate: 95,
    responsible: 'Fernanda Rocha',
    phone: '(41) 99789-0011',
    birthDate: '27/02/2010',
    observations: [
      {
        id: 'obs-12',
        date: '20/05/2024',
        time: '10:30',
        teacher: 'Prof. Lucas Silva',
        subject: 'Matemática',
        status: 'present',
        description: 'Parabéns pela dedicação na preparação para a Olimpíada.',
      },
    ],
  },
];

export const historyRecords: HistoryRecord[] = [
  {
    id: 'hist-1',
    date: '24/05/2024',
    classId: '6a',
    present: 22,
    absent: 3,
    late: 2,
    excused: 1,
    isLocked: true,
    studentRecords: { 1: 'present', 2: 'absent', 3: 'late', 4: 'excused', 5: 'present', 6: 'present', 7: 'present' },
  },
  {
    id: 'hist-2',
    date: '23/05/2024',
    classId: '6a',
    present: 24,
    absent: 1,
    late: 1,
    excused: 2,
    isLocked: true,
    studentRecords: { 1: 'present', 2: 'present', 3: 'late', 4: 'excused', 5: 'present', 6: 'present', 7: 'present' },
  },
  {
    id: 'hist-3',
    date: '22/05/2024',
    classId: '6a',
    present: 20,
    absent: 4,
    late: 1,
    excused: 3,
    isLocked: true,
    studentRecords: { 1: 'present', 2: 'absent', 3: 'absent', 4: 'excused', 5: 'present', 6: 'present', 7: 'excused' },
  },
  {
    id: 'hist-4',
    date: '21/05/2024',
    classId: '7b',
    present: 23,
    absent: 2,
    late: 1,
    excused: 0,
    isLocked: true,
    studentRecords: { 8: 'present', 9: 'absent' },
  },
  {
    id: 'hist-5',
    date: '20/05/2024',
    classId: '8a',
    present: 25,
    absent: 1,
    late: 1,
    excused: 0,
    isLocked: true,
    studentRecords: { 10: 'present' },
  },
];


export const teachers: Teacher[] = [
  {
    id: 't1',
    name: 'Prof. Lucas Silva',
    email: 'lucas.silva@classconecta.com.br',
    subject: 'Matemática',
    classIds: ['6a', '7b', '8a'],
    status: 'active',
  },
  {
    id: 't2',
    name: 'Profa. Mariana Costa',
    email: 'mariana.costa@classconecta.com.br',
    subject: 'Língua Portuguesa',
    classIds: ['6a', '7b'],
    status: 'active',
  },
  {
    id: 't3',
    name: 'Prof. Roberto Ferreira',
    email: 'roberto.ferreira@classconecta.com.br',
    subject: 'História & Geografia',
    classIds: ['8a'],
    status: 'active',
  },
  {
    id: 't4',
    name: 'Profa. Juliana Andrade',
    email: 'juliana.andrade@classconecta.com.br',
    subject: 'Ciências',
    classIds: [],
    status: 'inactive',
  },
];

export const staffMembers: StaffMember[] = [
  {
    id: 's1',
    name: 'Ana Costa',
    email: 'ana.costa@classconecta.com.br',
    roleTitle: 'Secretária Geral',
    department: 'Secretaria Acadêmica',
  },
  {
    id: 's2',
    name: 'Carlos Alberto Souza',
    email: 'carlos.souza@classconecta.com.br',
    roleTitle: 'Assistente Administrativo',
    department: 'Atendimento & Matrículas',
  },
  {
    id: 's3',
    name: 'Beatriz Ramos',
    email: 'beatriz.ramos@classconecta.com.br',
    roleTitle: 'Operadora de Registros',
    department: 'Documentação Escolar',
  },
];

export const operatorMembers: OperatorMember[] = [
  {
    id: 'op1',
    name: 'Rafael Lima',
    email: 'rafael.lima@classconecta.com.br',
    authorizedClassIds: ['6a', '7b'],
    accessType: 'Temporário',
    validUntil: '30/06/2024',
  },
  {
    id: 'op2',
    name: 'Camila Nogueira',
    email: 'camila.nogueira@classconecta.com.br',
    authorizedClassIds: ['8a'],
    accessType: 'Permanente',
  },
];

